name: Build OpenWrt package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/24.10.4/targets/ramips/mt76x8/openwrt-sdk-24.10.4-ramips-mt76x8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        tar --zstd -xf openwrt-sdk-*.tar.zst
        mv openwrt-sdk-* openwrt-sdk

    - name: Copy package
      run: |
        cp -r openwrt/package/youtubeunblock openwrt-sdk/package/

    - name: Build package
      working-directory: openwrt-sdk
      run: |
        make defconfig
        make package/youtubeunblock/compile V=s

    - name: Upload ipk
      uses: actions/upload-artifact@v4
      with:
        name: youtubeunblock-ipk
        path: openwrt-sdk/bin/packages/ramips/mt76x8/*.ipk
